-- 152_migration_platform_posts.sql
--
-- Adds an admin-only "platform posts" feature to the Living Universe page — Inkroot staff can
-- post an update that every signed-in writer can read, react to, and comment on. Fully additive:
-- nothing existing is modified except content_reports' content_type check constraint (already
-- extended this same way for book_discussion_post — see 68_migration_report_book_discussion_
-- posts.sql — and before that for account — see 31_migration_report_accounts_directly.sql).
--
-- Modeled directly on fireside_posts/fireside_reactions (schema.sql), with two differences that
-- fall out of platform_posts being global rather than guild-scoped: no guild_id column, and read
-- access is "any signed-in user" rather than "guild members only" (there's no guild to check
-- membership against). Comments are their own table (platform_post_comments) rather than
-- self-referencing replies the way fireside_posts uses parent_id, since a "reply to a reply"
-- thread isn't part of this feature.
--
-- Both platform_posts and platform_post_comments carry moderator soft-hide support
-- (removed_by_moderator + moderator read/remove policies) from creation, same shape as
-- published_books/fireside_posts/reviews/guild_book_feedback/book_discussion_posts (see
-- 78_migration_moderator_content_removal.sql) — needed because both are reportable content_types
-- below, and a report with nothing a moderator can act on isn't a complete feature. This reuses
-- that migration's protect_content_from_moderator_edits() function unmodified; nothing about that
-- function or any of the five tables it already covers is touched here.
--
-- Do not edit this file in place once it has run anywhere — redefine via a new migration,
-- exactly as every other migration in this repo does.

-- ---------- platform_posts ----------
create table if not exists platform_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) <= 200),
  -- Same 8000-char cap as fireside_posts.body — see 22_migration_text_field_length_caps.sql.
  body text not null check (char_length(body) <= 8000),
  image_url text,
  author_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  -- Soft-hide flag, same shape as published_books/fireside_posts/reviews/guild_book_feedback/
  -- book_discussion_posts (see 78_migration_moderator_content_removal.sql) — included from the
  -- table's own creation here rather than added by a later ALTER, since this whole feature ships
  -- in one pass. protect_content_from_moderator_edits() below is that same migration's existing
  -- function, reused as-is (not redefined) — it already takes the author column name as an
  -- argument, so no repo change is needed for it to cover this table too.
  removed_by_moderator boolean not null default false
);

alter table platform_posts enable row level security;

-- Same "author can still see their own removed post, everyone else can't, moderators always can"
-- shape as every other soft-hideable table (see 78_migration_moderator_content_removal.sql).
create policy "signed-in readers read platform posts" on platform_posts
  for select using (
    auth.uid() is not null and (not removed_by_moderator or auth.uid() = author_id)
  );
create policy "moderators read all platform posts" on platform_posts
  for select using (
    exists (select 1 from profiles p where p.id = auth.uid() and p.is_moderator)
  );

-- Insert requires both platform-admin standing (same inline exists(...) style as migration
-- 80_migration_fireside_announcement_officer_gate.sql, not an is_platform_admin() wrapper
-- function, to stay consistent with that file) and the ban check every other content-creating
-- policy in this repo carries. auth.uid() = author_id is required too, matching every other
-- content-creating policy in this repo (fireside_posts, reviews, ...) — without it, an admin's
-- insert could claim authorship of any account.
create policy "platform admins post platform posts" on platform_posts
  for insert with check (
    auth.uid() = author_id
    and not is_banned(auth.uid())
    and exists (select 1 from profiles p where p.id = auth.uid() and p.is_platform_admin)
  );

-- Moderator removal — same shape as every other soft-hideable table. The column-level safety net
-- (a moderator's update may only touch removed_by_moderator, nothing else) is enforced by
-- protect_content_from_moderator_edits(), reused unmodified from migration 78.
create policy "moderators remove platform posts" on platform_posts
  for update using (
    exists (select 1 from profiles p where p.id = auth.uid() and p.is_moderator)
  );
drop trigger if exists protect_from_moderator_edits on platform_posts;
create trigger protect_from_moderator_edits
  before update on platform_posts
  for each row execute function protect_content_from_moderator_edits('author_id');

create index if not exists platform_posts_created_idx on platform_posts (created_at desc);

-- ---------- platform_post_reactions ----------
-- One row per (post, reader, reaction kind), same shape as fireside_reactions — avoids
-- read-modify-write races and lets RLS scope "a reader manages their own reaction" cleanly.
create table if not exists platform_post_reactions (
  post_id uuid not null references platform_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id, reaction)
);

alter table platform_post_reactions enable row level security;

create policy "signed-in readers read platform post reactions" on platform_post_reactions
  for select using (auth.uid() is not null);

-- No admin gate here — any signed-in, non-banned reader can react to a platform post.
create policy "a reader adds their own platform post reaction" on platform_post_reactions
  for insert with check (auth.uid() = user_id and not is_banned(auth.uid()));

create policy "a reader removes their own platform post reaction" on platform_post_reactions
  for delete using (auth.uid() = user_id);

-- ---------- platform_post_comments ----------
create table if not exists platform_post_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references platform_posts(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  -- Same 8000-char cap as fireside_posts.body — see 22_migration_text_field_length_caps.sql.
  body text not null check (char_length(body) <= 8000),
  created_at timestamptz not null default now(),
  -- Reportable as its own content_type ('platform_post_comment', see below), so it needs its own
  -- removal flag independent of its parent post's — same reasoning as platform_posts above.
  removed_by_moderator boolean not null default false
);

alter table platform_post_comments enable row level security;

create policy "signed-in readers read platform post comments" on platform_post_comments
  for select using (
    auth.uid() is not null and (not removed_by_moderator or auth.uid() = author_id)
  );
create policy "moderators read all platform post comments" on platform_post_comments
  for select using (
    exists (select 1 from profiles p where p.id = auth.uid() and p.is_moderator)
  );

create policy "a reader adds their own platform post comment" on platform_post_comments
  for insert with check (auth.uid() = author_id and not is_banned(auth.uid()));

create policy "moderators remove platform post comments" on platform_post_comments
  for update using (
    exists (select 1 from profiles p where p.id = auth.uid() and p.is_moderator)
  );
drop trigger if exists protect_from_moderator_edits on platform_post_comments;
create trigger protect_from_moderator_edits
  before update on platform_post_comments
  for each row execute function protect_content_from_moderator_edits('author_id');

create index if not exists platform_post_comments_post_idx on platform_post_comments (post_id, created_at asc);

-- Posting-cooldown trigger, copied from enforce_fireside_post_cooldown() (see
-- 76_migration_fireside_post_cooldown.sql) — same 15-second window, same
-- pg_advisory_xact_lock-per-author pattern, renamed for this table so the two locks (keyed by a
-- string prefix + author id) never collide with each other.
create or replace function enforce_platform_post_comment_cooldown()
returns trigger as $$
declare
  v_last_comment_at timestamptz;
  v_cooldown interval := interval '15 seconds';
begin
  perform pg_advisory_xact_lock(hashtext('platform_post_comment_cooldown:' || new.author_id::text));

  select max(created_at) into v_last_comment_at
  from platform_post_comments where author_id = new.author_id;

  if v_last_comment_at is not null and now() - v_last_comment_at < v_cooldown then
    raise exception 'You''re posting too quickly — please wait a few seconds before posting again.';
  end if;

  return new;
end;
$$ language plpgsql;

drop trigger if exists platform_post_comment_cooldown_trigger on platform_post_comments;
create trigger platform_post_comment_cooldown_trigger
  before insert on platform_post_comments
  for each row execute function enforce_platform_post_comment_cooldown();

-- ---------- content_reports: allow reporting platform posts/comments ----------
-- Same drop + recreate style as 68_migration_report_book_discussion_posts.sql. Every other
-- content_type already in this list (published_book, guild_published_book, fireside_post,
-- guild_book_feedback, review, account, book_discussion_post — the last added by migration 68)
-- is carried over unchanged; only platform_post/platform_post_comment are new.
alter table content_reports drop constraint if exists content_reports_content_type_check;
alter table content_reports add constraint content_reports_content_type_check
  check (content_type in (
    'published_book', 'guild_published_book', 'fireside_post', 'guild_book_feedback', 'review',
    'account', 'book_discussion_post', 'platform_post', 'platform_post_comment'
  ));

-- ---------- storage: admin-only images for platform posts ----------
-- New policies only — the existing "anyone can read public media" / "a writer uploads their own
-- media" policies on storage.objects (schema_phase9.sql) are untouched. mediaStorage.js already
-- routes any folder not in its PRIVATE_FOLDERS set (currently just 'project-images') to the
-- public 'media' bucket, so uploadImageDataUrl(dataUrl, 'platform-posts') needs no code change to
-- land here — only these policies need to exist for it to be allowed and readable.
--
-- Deliberately NOT added to is_public_media_folder() (see 19_migration_dedupe_public_media_
-- folder_list.sql / 45_migration_guild_event_creation_workflow.sql), even though that's this
-- repo's usual way to extend the public-media allowlist. That function is shared by all four
-- storage.objects policies — select AND the three owner-scoped write ones, which additionally
-- require auth.uid()::text = (storage.foldername(name))[2] ("you may write your own uid's
-- subfolder"). avatars/guild-crests/book-covers/guild-event-covers are all genuinely
-- owner-written, so that shape fits them. platform-posts is admin-written, not owner-written —
-- folding it into is_public_media_folder() would make the *existing* generic write policies
-- additionally permit any signed-in user to upload to platform-posts/<their own uid>/..., since
-- Postgres OR's multiple permissive policies together. Four standalone policies here (one of
-- which duplicates the public-read shape) is the smaller, safer cost versus reopening that hole.
create policy "anyone can read platform post images" on storage.objects
  for select using (
    bucket_id = 'media' and (storage.foldername(name))[1] = 'platform-posts'
  );

create policy "platform admins upload platform post images" on storage.objects
  for insert with check (
    bucket_id = 'media'
    and (storage.foldername(name))[1] = 'platform-posts'
    and exists (select 1 from profiles p where p.id = auth.uid() and p.is_platform_admin)
  );

create policy "platform admins update platform post images" on storage.objects
  for update using (
    bucket_id = 'media'
    and (storage.foldername(name))[1] = 'platform-posts'
    and exists (select 1 from profiles p where p.id = auth.uid() and p.is_platform_admin)
  );

create policy "platform admins delete platform post images" on storage.objects
  for delete using (
    bucket_id = 'media'
    and (storage.foldername(name))[1] = 'platform-posts'
    and exists (select 1 from profiles p where p.id = auth.uid() and p.is_platform_admin)
  );

-- No Realtime publication added here (unlike fireside_posts/fireside_reactions in schema.sql) —
-- not asked for in this pass, and platform-posts.js below has no subscribe function to consume
-- it. The feed refetches on its own actions instead, same as FiresideBoard's non-remote fallback
-- mode. A reasonable, self-contained follow-up if live updates are wanted later.

-- APPLIED TO PRODUCTION and verified via read-only schema audit against project cfabvlgpsemixhbedvzt
-- (2026-09-26): live table/RLS/policy/trigger/index definitions match this file exactly. Do not
-- edit this file in place going forward — redefine via a new migration, per this repo's convention.
