-- 153_migration_platform_posts_v2.sql
--
-- Expands platform_posts (152_migration_platform_posts.sql) with the fields and admin controls
-- that pass asked for up front but weren't in the first cut: a post_type category, a real
-- draft/published/hidden status the admin controls (kept separate from moderator removal),
-- updated_at bookkeeping, a polymorphic optional attachment to a Book/Guild/World/Event, and the
-- ability for any platform admin to edit or hide any post (not just their own). Fully additive to
-- 152 — no table it created is dropped, no column it added is removed, no existing row shape
-- changes meaning.
--
-- Two shared functions are redefined in place (same technique already used by migration 150 for
-- protect_content_from_moderator_edits and moderator_set_content_removed) rather than duplicated:
--
--   1. moderator_set_content_removed() currently only recognizes 5 tables
--      ('published_books', 'fireside_posts', 'reviews', 'guild_book_feedback',
--      'book_discussion_posts') — platform_posts/platform_post_comments were never added to its
--      allow-list when 152 shipped. That's a real, pre-existing bug: the "moderators remove
--      platform posts" RLS policy lets a moderator's UPDATE through, but
--      protect_content_from_moderator_edits() (below) refuses to let removed_by_moderator change
--      on ANY table unless this RPC set the trusted flag first — and this RPC has always rejected
--      platform_posts/platform_post_comments as an "Unknown content table". So today, a moderator
--      cannot actually remove a reported platform post at all, despite the UI/policy suggesting
--      they can. Fixed here by adding two more branches to this same function — the 5 existing
--      branches are byte-for-byte unchanged.
--
--   2. protect_content_from_moderator_edits() gets one narrow, scoped exception added ahead of
--      its existing "a moderator acting on someone else's content may only change
--      removed_by_moderator" check: when the update is on platform_posts AND a transaction-local
--      flag (inkroot.trusted_platform_post_admin_edit) is set, that restriction is skipped. This
--      is needed because platform admin and moderator are separate flags (see fetchIsPlatformAdmin
--      / fetchIsModerator in lib/moderation.js) — an account that happens to carry both, editing
--      a DIFFERENT admin's post, would otherwise get its edit narrowed to "only
--      removed_by_moderator" by the same rule that (correctly) restricts a moderator acting on
--      someone else's content. Only admin_update_platform_post() (below) ever sets this flag, and
--      only for platform_posts — the other five tables this function guards are byte-for-byte
--      unaffected; TG_TABLE_NAME is checked explicitly. The existing, separate
--      "removed_by_moderator can only change via moderator_set_content_removed()" lock is left
--      completely untouched below — admin_update_platform_post() never touches that column, so it
--      never needs to pass that check in the first place.
--
-- Do not edit this file in place once it has run anywhere — redefine via a new migration, exactly
-- as every other migration in this repo does.

-- ---------- platform_posts: new columns ----------

-- post_type: which of the six Living Universe categories this post is. NOT NULL with a default
-- (rather than no default) because this is an ALTER on a table that may already have rows in any
-- environment this has been tried against; 'inkroot_update' is the safest catch-all default for
-- any such row. Every future insert/edit from the app always sends an explicit value — see
-- platform-posts.js — so the default is a backstop, not a real choice.
alter table platform_posts add column if not exists post_type text not null default 'inkroot_update';
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'platform_posts_post_type_check') then
    alter table platform_posts add constraint platform_posts_post_type_check check (
      post_type in (
        'book_spotlight', 'worldbuilding_showcase', 'guild_announcement',
        'writing_tip', 'inkroot_update', 'event_announcement'
      )
    );
  end if;
end $$;

-- status: the admin-controlled visibility state, independent of removed_by_moderator (a
-- moderator's soft-hide for reported content). Defaults to 'draft' — a newly inserted row is
-- never visible to a regular reader until an admin explicitly publishes it. The app's composer
-- always sends an explicit status either way (see platform-posts.js), so this default only
-- matters for a row inserted outside that path.
alter table platform_posts add column if not exists status text not null default 'draft';
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'platform_posts_status_check') then
    alter table platform_posts add constraint platform_posts_status_check check (
      status in ('draft', 'published', 'hidden')
    );
  end if;
end $$;

-- updated_at: bookkeeping only, same pattern as published_books/player_guilds/
-- guild_order_chapters. Bumped by the trigger below on every update, moderator or admin.
alter table platform_posts add column if not exists updated_at timestamptz not null default now();

-- attached_type / attached_id: optional polymorphic reference to an existing Book, Guild, World
-- (Guild World Bible entry), or Event. No foreign key — the four targets live in different
-- tables with different id types (published_books.id and guild_published_books.id are different
-- types from each other; player_guilds.id, guild_order_world_entries.id, and guild_events.id are
-- uuid but in unrelated tables), so a single FK column can't reference all of them. attached_id is
-- stored as text for the same reason published_books.id already is text elsewhere in this schema.
-- Resolving attached_id to a real row (and deciding whether the viewer is even allowed to see it)
-- is left entirely to the reader's own RLS-scoped SELECT at render time — see
-- fetchAttachmentPreview in platform-posts.js — never to a privileged/bypassing lookup, so this
-- column can never be used to leak a Guild World Bible entry or a guild-only book listing to a
-- reader who couldn't already see it directly.
alter table platform_posts add column if not exists attached_type text;
alter table platform_posts add column if not exists attached_id text;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'platform_posts_attached_type_check') then
    alter table platform_posts add constraint platform_posts_attached_type_check check (
      attached_type is null or attached_type in ('book', 'guild', 'world', 'event')
    );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'platform_posts_attachment_pair_check') then
    alter table platform_posts add constraint platform_posts_attachment_pair_check check (
      (attached_type is null) = (attached_id is null)
    );
  end if;
end $$;

create index if not exists platform_posts_status_idx on platform_posts (status) where status = 'published';
create index if not exists platform_posts_attachment_idx on platform_posts (attached_type, attached_id)
  where attached_type is not null;

-- updated_at bookkeeping trigger — same shape as touch_guild_order_chapters_updated_at(). Trigger
-- name is deliberately alphabetically after "protect_from_moderator_edits" (the existing trigger
-- on this table from 152), so Postgres's alphabetical same-event trigger ordering runs the
-- moderator/removal guard first and this touch second: protect_content_from_moderator_edits()
-- below inspects NEW vs OLD to decide what changed, and must see that diff before this trigger
-- adds an updated_at difference of its own.
create or replace function touch_platform_posts_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists touch_platform_posts_updated_at_trigger on platform_posts;
create trigger touch_platform_posts_updated_at_trigger
  before update on platform_posts
  for each row execute function touch_platform_posts_updated_at();

-- ---------- platform_posts: read policy now accounts for status ----------
-- Replaces 152's single "signed-in readers read platform posts" policy. A regular reader now
-- needs status = 'published' (in addition to the existing not-moderator-removed check) unless
-- they're the post's own author, who can still see their own drafts/hidden posts, same "author
-- always sees their own" shape as every other soft-hideable table in this repo.
drop policy if exists "signed-in readers read platform posts" on platform_posts;
create policy "signed-in readers read platform posts" on platform_posts
  for select using (
    auth.uid() is not null
    and (
      auth.uid() = author_id
      or (status = 'published' and not removed_by_moderator)
    )
  );

-- New — a platform admin managing Universe Posts needs to see every post regardless of status
-- (including other admins' drafts/hidden posts and moderator-removed ones), same shape as the
-- existing "moderators read all platform posts" policy just below it.
create policy "platform admins read all platform posts" on platform_posts
  for select using (
    exists (select 1 from profiles p where p.id = auth.uid() and p.is_platform_admin)
  );

-- New — lets any platform admin's edit/hide go through (via admin_update_platform_post() below).
-- No client insert/update policy pattern was an option here (unlike guild_events), since create
-- stays a direct client insert (152's own policy, untouched) and only edits need admin-wide
-- reach; this is scoped to UPDATE only and mirrors "moderators remove platform posts" exactly.
create policy "platform admins update platform posts" on platform_posts
  for update using (
    exists (select 1 from profiles p where p.id = auth.uid() and p.is_platform_admin)
  );

-- ---------- admin_update_platform_post(): the only way an admin edits/hides a post ----------
-- security definer so it can update a post authored by a different admin; auth.uid() is still the
-- real caller throughout (security definer changes execution privilege, not session identity), so
-- every check below is against the actual signed-in admin, not the function owner. Handles both
-- "edit" and "hide" — hide is simply calling this with status = 'hidden' and the rest unchanged;
-- there is deliberately no separate delete path (platform posts are never hard-deleted, so
-- comments/reactions/report history are always preserved — see the migration header above).
create or replace function admin_update_platform_post(
  p_id uuid,
  p_title text,
  p_body text,
  p_image_url text,
  p_post_type text,
  p_status text,
  p_attached_type text,
  p_attached_id text
)
returns platform_posts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_is_admin boolean;
  v_title text := btrim(coalesce(p_title, ''));
  v_body text := btrim(coalesce(p_body, ''));
  v_prev platform_posts;
  v_new platform_posts;
begin
  select p.is_platform_admin into v_is_admin from profiles p where p.id = auth.uid();
  if not coalesce(v_is_admin, false) then
    raise exception 'Only a platform admin can edit a platform post.';
  end if;
  if is_banned(auth.uid()) then
    raise exception 'Your account cannot perform this action.';
  end if;
  if v_title = '' or v_body = '' then
    raise exception 'A post needs a title and a body.';
  end if;
  if p_status not in ('draft', 'published', 'hidden') then
    raise exception 'Unknown status.';
  end if;
  if p_post_type not in (
    'book_spotlight', 'worldbuilding_showcase', 'guild_announcement',
    'writing_tip', 'inkroot_update', 'event_announcement'
  ) then
    raise exception 'Unknown post type.';
  end if;
  if p_attached_type is not null and p_attached_type not in ('book', 'guild', 'world', 'event') then
    raise exception 'Unknown attachment type.';
  end if;
  if (p_attached_type is null) <> (p_attached_id is null) then
    raise exception 'An attachment needs both a type and an id.';
  end if;

  select * into v_prev from platform_posts where id = p_id;
  if not found then
    raise exception 'Post not found.';
  end if;

  -- Scoped narrowly to platform_posts (see protect_content_from_moderator_edits() below) — an
  -- admin who also happens to be a moderator editing someone else's post must not get narrowed
  -- down to "only removed_by_moderator" by that function's moderator-scope check.
  perform set_config('inkroot.trusted_platform_post_admin_edit', 'true', true);

  update platform_posts set
    title = v_title,
    body = v_body,
    image_url = p_image_url,
    post_type = p_post_type,
    status = p_status,
    attached_type = p_attached_type,
    attached_id = p_attached_id
  where id = p_id
  returning * into v_new;

  perform record_admin_action(
    'update_platform_post',
    'platform_posts',
    p_id,
    to_jsonb(v_prev),
    to_jsonb(v_new)
  );

  return v_new;
end;
$$;

revoke all on function admin_update_platform_post(uuid, text, text, text, text, text, text, text) from public;
grant execute on function admin_update_platform_post(uuid, text, text, text, text, text, text, text) to authenticated;

-- ---------- moderator_set_content_removed(): add platform_posts / platform_post_comments ----------
-- Redefined in place. The 5 existing branches (published_books, fireside_posts, reviews,
-- guild_book_feedback, book_discussion_posts) are byte-for-byte identical to
-- 150_migration_moderation_removal_audit_log.sql — only the allow-list and the two new elsif
-- branches below are new.
create or replace function moderator_set_content_removed(p_table text, p_id text, p_removed boolean, p_reason text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_is_mod boolean;
  v_target_id uuid;
  v_prev boolean;
  v_clean_reason text := nullif(trim(coalesce(p_reason, '')), '');
begin
  select is_moderator into v_is_mod from profiles where id = auth.uid();
  if not coalesce(v_is_mod, false) then
    raise exception 'Only a moderator can remove or restore content.';
  end if;
  if p_table not in (
    'published_books', 'fireside_posts', 'reviews', 'guild_book_feedback', 'book_discussion_posts',
    'platform_posts', 'platform_post_comments'
  ) then
    raise exception 'Unknown content table.';
  end if;
  if p_removed and v_clean_reason is null then
    raise exception 'A reason is required to remove content.';
  end if;

  perform set_config('inkroot.trusted_moderation_rpc', 'true', true);

  if p_table = 'published_books' then
    select removed_by_moderator into v_prev from published_books where id = p_id;
    if not found then raise exception 'Content not found.'; end if;
    update published_books set removed_by_moderator = p_removed where id = p_id;
    v_target_id := null;
  elsif p_table = 'fireside_posts' then
    select removed_by_moderator into v_prev from fireside_posts where id = p_id::uuid;
    if not found then raise exception 'Content not found.'; end if;
    update fireside_posts set removed_by_moderator = p_removed where id = p_id::uuid;
    v_target_id := p_id::uuid;
  elsif p_table = 'reviews' then
    select removed_by_moderator into v_prev from reviews where id = p_id::uuid;
    if not found then raise exception 'Content not found.'; end if;
    update reviews set removed_by_moderator = p_removed where id = p_id::uuid;
    v_target_id := p_id::uuid;
  elsif p_table = 'guild_book_feedback' then
    select removed_by_moderator into v_prev from guild_book_feedback where id = p_id::uuid;
    if not found then raise exception 'Content not found.'; end if;
    update guild_book_feedback set removed_by_moderator = p_removed where id = p_id::uuid;
    v_target_id := p_id::uuid;
  elsif p_table = 'platform_posts' then
    select removed_by_moderator into v_prev from platform_posts where id = p_id::uuid;
    if not found then raise exception 'Content not found.'; end if;
    update platform_posts set removed_by_moderator = p_removed where id = p_id::uuid;
    v_target_id := p_id::uuid;
  elsif p_table = 'platform_post_comments' then
    select removed_by_moderator into v_prev from platform_post_comments where id = p_id::uuid;
    if not found then raise exception 'Content not found.'; end if;
    update platform_post_comments set removed_by_moderator = p_removed where id = p_id::uuid;
    v_target_id := p_id::uuid;
  else
    select removed_by_moderator into v_prev from book_discussion_posts where id = p_id::uuid;
    if not found then raise exception 'Content not found.'; end if;
    update book_discussion_posts set removed_by_moderator = p_removed where id = p_id::uuid;
    v_target_id := p_id::uuid;
  end if;

  perform record_admin_action(
    case when p_removed then 'remove_content' else 'restore_content' end,
    p_table,
    v_target_id,
    jsonb_build_object('id', p_id, 'removed_by_moderator', v_prev),
    jsonb_build_object('id', p_id, 'removed_by_moderator', p_removed),
    null,
    v_clean_reason
  );
end;
$$;

revoke all on function moderator_set_content_removed(text, text, boolean, text) from public;
grant execute on function moderator_set_content_removed(text, text, boolean, text) to authenticated;

-- ---------- protect_content_from_moderator_edits(): scoped admin-edit exception ----------
-- Redefined in place. Same six tables now use this trigger (platform_post_comments' own trigger
-- is untouched — it isn't part of this exception, only platform_posts is). Everything below is
-- byte-for-byte identical to the version in 150_migration_moderation_removal_audit_log.sql except
-- the one added "and not (...)" clause on the first check, called out below.
create or replace function protect_content_from_moderator_edits()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  acting_is_moderator boolean;
  author_column text := TG_ARGV[0];
  old_owner uuid;
begin
  select p.is_moderator into acting_is_moderator from profiles p where p.id = auth.uid();
  execute format('select ($1).%I', author_column) into old_owner using old;

  if coalesce(acting_is_moderator, false) and auth.uid() is distinct from old_owner
     -- Added here only: a platform admin's edit (via admin_update_platform_post(), the only
     -- setter of this flag) is exempt from the moderator-scope restriction below, on
     -- platform_posts only. The other five tables this trigger guards never set this flag, so
     -- their behavior is unchanged.
     and not (
       TG_TABLE_NAME = 'platform_posts'
       and coalesce(current_setting('inkroot.trusted_platform_post_admin_edit', true), '') = 'true'
     ) then
    if (to_jsonb(new) - 'removed_by_moderator') is distinct from (to_jsonb(old) - 'removed_by_moderator') then
      raise exception 'A moderator acting on someone else''s content may only change removed_by_moderator.';
    end if;
  end if;

  -- Unchanged from migration 150: removed_by_moderator itself may only change via
  -- moderator_set_content_removed() — admin_update_platform_post() never touches this column, so
  -- it never needs to satisfy this check.
  if new.removed_by_moderator is distinct from old.removed_by_moderator
     and coalesce(current_setting('inkroot.trusted_moderation_rpc', true), '') <> 'true' then
    raise exception 'removed_by_moderator can only be changed via moderator_set_content_removed().';
  end if;

  return new;
end;
$$;

-- APPLIED TO PRODUCTION and verified via read-only schema audit against project cfabvlgpsemixhbedvzt
-- (2026-09-26): live schema/functions/policies match this file exactly, including both redefined-
-- in-place functions (moderator_set_content_removed, protect_content_from_moderator_edits). Do not
-- edit this file in place going forward — redefine via a new migration, per this repo's convention.
